name: Git Checkout Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: List Files before
        run: ls -la
      - name: checkout
        uses: actions/checkout@v3
      - name: List Files After
        run: ls -la
        